# Generated by Django 3.2.7 on 2021-09-02 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_alter_customuser_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users_photos/', verbose_name='Фотография профиля'),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Перевод суммы')),
                ('confirmation_of_transfer', models.BooleanField(default=False, verbose_name='Подтверждение операции')),
                ('receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_user', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_user', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'История операции',
                'verbose_name_plural': 'История операций',
                'db_table': 'operation',
            },
        ),
    ]
